// Code generated by mockery v1.0.0. DO NOT EDIT.

package data

import mock "github.com/stretchr/testify/mock"

// MockDepositIDGenerator is an autogenerated mock type for the DepositIDGenerator type
type MockDepositIDGenerator struct {
	mock.Mock
}

// Generate provides a mock function with given fields:
func (_m *MockDepositIDGenerator) Generate() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
