{{- $fullName := include "service.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $fullName }}"
  labels:
{{ include "service.labels" . | indent 4 }}
type: Opaque
data:
  config.yaml: {{ toYaml .Values.configYaml | b64enc | quote }}